services:
  user_management_service:
    build:
      context: ../user_management_service
      dockerfile: ../docker/images/user_management.Dockerfile
    ports:
      - "8000:8000"
  
  mailer_service:
    build:
      context: ../mailer_service
      dockerfile: ../docker/images/mailer.Dockerfile
    ports:
      - "8001:8000"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: mailer_db
    ports: 
      - "5433:5432"
    volumes:
      - ${PWD}/docker/images/init-db-real.sh:/docker-entrypoint-initdb.d/init-db-real.sh
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:3.9.3
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:4.0.0
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
    depends_on: 
      - zookeeper

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  postgres_data:
  redis_data:

